CREATE TABLE matchs(  
  id SERIAL PRIMARY KEY,
  issuer INT NOT NULL REFERENCES cats(id) ON DELETE CASCADE,
  receiver INT NOT NULL REFERENCES cats(id) ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  status VARCHAR(255) NOT NULL
);